<a href="https://colab.research.google.com/github/Amoako419/Learning_ML/blob/main/CNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [25]:
from tensorflow.keras.datasets import mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D
from tensorflow.keras.layers import MaxPool2D
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Dropout
from tensorflow.keras.layers import Dense
from tensorflow.keras.losses import SparseCategoricalCrossentropy

In [2]:
(X_train, y_train), (X_test, y_test) = mnist.load_data()

11490434/11490434 [==============================] - 1s 0us/step


In [3]:
X_train = X_train.reshape((X_train.shape[0]), X_train.shape[1],X_train.shape[2],1)

In [4]:
X_test = X_test.reshape((X_test.shape[0],X_test.shape[1],X_test.shape[2],1))

In [5]:
print(X_train.shape)
print(X_test.shape)

(60000, 28, 28, 1)
(10000, 28, 28, 1)


In [6]:
X_train = X_train/255
X_test = X_test/255

In [7]:
print(X_train)
print(X_test)

[[[[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  ...

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]]


 [[[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  ...

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]]


 [[[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  ...

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.

In [8]:
print(y_train)
print(y_test)

[5 0 4 ... 5 6 8]
[7 2 1 ... 4 5 6]


In [9]:
model = Sequential()

In [10]:
model.add(Conv2D(32,(3,3),activation = 'relu',input_shape =(28,28,1)))

In [11]:
model.add(MaxPool2D(2,2))

In [12]:
model.add(Flatten())
model.add(Dense(100, activation = 'relu'))

In [13]:
model.add(Dense(10,activation= 'softmax'))

In [26]:
model.compile(loss=SparseCategoricalCrossentropy(), optimizer='adam', metrics=['accuracy'])

In [27]:
model.fit(X_train, y_train, epochs=10)

Epoch 1/10
1875/1875 [==============================] - 39s 20ms/step - loss: 0.1504 - accuracy: 0.9561
Epoch 2/10
1875/1875 [==============================] - 37s 20ms/step - loss: 0.0529 - accuracy: 0.9841
Epoch 3/10
1875/1875 [==============================] - 38s 20ms/step - loss: 0.0341 - accuracy: 0.9896
Epoch 4/10
1875/1875 [==============================] - 37s 20ms/step - loss: 0.0218 - accuracy: 0.9932
Epoch 5/10
1875/1875 [==============================] - 37s 20ms/step - loss: 0.0163 - accuracy: 0.9945
Epoch 6/10
1875/1875 [==============================] - 38s 20ms/step - loss: 0.0120 - accuracy: 0.9961
Epoch 7/10
1875/1875 [==============================] - 37s 20ms/step - loss: 0.0085 - accuracy: 0.9971
Epoch 8/10
1875/1875 [==============================] - 37s 20ms/step - loss: 0.0072 - accuracy: 0.9974
Epoch 9/10
1875/1875 [==============================] - 37s 20ms/step - loss: 0.0057 - accuracy: 0.9980
Epoch 10/10
1875/1875 [==============================] - 37s 20m

In [29]:
model.evaluate(X_test,y_test)

313/313 [==============================] - 2s 7ms/step - loss: 0.0577 - accuracy: 0.9867


[0.057720769196748734, 0.9866999983787537]