In [9]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix

In [2]:
dataset = pd.read_csv('knn.csv')
dataset

User ID  Gender  Age  EstimatedSalary  Purchased
0   15624510   Male    19             1900          0
1   15624510   Male    19            20000          0
2   15624510   Male    25            43000          0
3   15624510   Male    26            57000          0
4   15624510   Male    26            76000          0
5   15624510   Male    19            58000          1
6   15624510   Male    18            84000          1
7   15624510  Female   19           150000          1
8   15624510  Female   22            33000          0
9   15624510  Female   19            65000          1
10  15624510  Female   21            80000          1
11  15624510  Female   19            52000          0
12  15624510  Female   19            86000          1
13  15624510  Female   33            18000          1
14  15624510   Male    48            82000          0
15  15624510   Male    19            80000          1
16  15624510   Male    45            25000          1
17  15624510  Female   55            26000          0
18  15624510  Female   20            28000          1
19  15624510  Female   29            29000          0
20  15624510    male   47            22000          1
21  15624510  Female   45            49000          1

In [6]:
dataset.EstimatedSalary[0] = 19000
dataset

/var/folders/qj/fxsf77sd1p38mdc08b1lfqrr0000gn/T/ipykernel_62617/3409397216.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset.EstimatedSalary[0] = 19000


User ID  Gender  Age  EstimatedSalary  Purchased
0   15624510   Male    19            19000          0
1   15624510   Male    19            20000          0
2   15624510   Male    25            43000          0
3   15624510   Male    26            57000          0
4   15624510   Male    26            76000          0
5   15624510   Male    19            58000          1
6   15624510   Male    18            84000          1
7   15624510  Female   19           150000          1
8   15624510  Female   22            33000          0
9   15624510  Female   19            65000          1
10  15624510  Female   21            80000          1
11  15624510  Female   19            52000          0
12  15624510  Female   19            86000          1
13  15624510  Female   33            18000          1
14  15624510   Male    48            82000          0
15  15624510   Male    19            80000          1
16  15624510   Male    45            25000          1
17  15624510  Female   55            26000          0
18  15624510  Female   20            28000          1
19  15624510  Female   29            29000          0
20  15624510    male   47            22000          1
21  15624510  Female   45            49000          1

In [10]:
#importin the dataset
x = dataset.iloc[:,2:4].values
y = dataset.iloc[:,4].values

In [11]:
x

array([[    19,  19000],
       [    19,  20000],
       [    25,  43000],
       [    26,  57000],
       [    26,  76000],
       [    19,  58000],
       [    18,  84000],
       [    19, 150000],
       [    22,  33000],
       [    19,  65000],
       [    21,  80000],
       [    19,  52000],
       [    19,  86000],
       [    33,  18000],
       [    48,  82000],
       [    19,  80000],
       [    45,  25000],
       [    55,  26000],
       [    20,  28000],
       [    29,  29000],
       [    47,  22000],
       [    45,  49000]])

In [12]:
y

array([0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1])

In [14]:
#Traing and Testing data
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size= 0.25, random_state = 0)

In [15]:
from sklearn.preprocessing import StandardScaler
sc_x = StandardScaler()
x_train = sc_x.fit_transform(x_train)
x_test = sc_x.fit_transform(x_test)

In [16]:
 print(x_train)

[[-5.84164818e-01 -1.51364607e-01]
 [ 3.99691718e-01 -8.56455433e-01]
 [-2.89007857e-01 -7.33830941e-01]
 [-6.82550472e-01  8.29631325e-01]
 [ 1.97386218e+00 -9.79079924e-01]
 [ 1.04534757e-01  5.84382342e-01]
 [ 6.14910335e-03 -4.27269713e-01]
 [-5.84164818e-01  3.25721306e-02]
 [ 2.95771871e+00 -9.48423802e-01]
 [-5.84164818e-01  2.47164991e-01]
 [-5.84164818e-01  2.85293544e+00]
 [-4.85779165e-01 -8.87111556e-01]
 [ 1.04534757e-01  1.91600768e-03]
 [-5.84164818e-01 -1.16301666e+00]
 [-5.84164818e-01  7.07006834e-01]
 [-5.84164818e-01  8.90943571e-01]]


In [17]:
print(x_test)

[[ 0.95639814 -0.84660148]
 [-1.20589331  1.27294754]
 [ 1.0395632   1.34603544]
 [-0.20791264 -0.99277727]
 [-1.37222342 -0.91968937]
 [ 0.79006803  0.14008514]]


In [23]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=5, metric="minkowski",p=2)
classifier.fit(x_train,y_train)

KNeighborsClassifier()

In [24]:
y_pred =classifier.predict(x_test)

cm = confusion_matrix(y_pred,y_test)
print(cm)
#Correct predictions = 1+1
#Incorrect predictions = 3+1

[[1 3]
 [1 1]]
